### ISSUE TITLE
-Inf error and suggested fix

### ISSUE THREAD

**Issue by christopherwirth** [cran/PLMIX#1]
Hi Cristina,

**Bug and suggested fix**:

We have encountered an error in _loglikPLMIX_. If there are a lot of columns in the matrix _p_ (i.e. a lot of events being considered), some values of _p_ can become very small. This can result in _loglikPLMIX_ returning _-Inf_. To fix this, I suggest adding:

```
while(weights[j]*exp(f) == 0) {
  f++;
}
```
...at line 68 of _PLMIX/code/loglikPLMIX.cpp_

**Explanation**:

 - the variable f is iteratively calculated by adding logs of the values in p
 - because individual values of p are << 1, their logs are negative
 - this results in an ever-more negative value for f
 - another variable h is calculated by a function of exp(f)
 - if f is too large a negative number (on my system, anything < -745), exp(f) = 0
 - therefore h remains as 0
 - variable ll (the log likelihood) is a sum of log(h) values
 - log(0) = -Inf

There is already what appears to be a failsafe in _mapPLMIX_ (the function in which _loglikPLMIX_ is called) for a similar case, where _loglikPLMIX_ returns _NA_ rather than _-Inf_. In an attempt to change the code as little as possible, I first tried to apply the same fix to our bug, by changing the lines:

`if (is.na(log_lik[l])) {
`
and
`while (is.na(log_lik[l]) & threshold < (-3)) {
`

to 

`if (is.na(log_lik[l]) || is.infinite(log_lik[l])) {
`
and
`while ((is.na(log_lik[l]) || is.infinite(log_lik[l])) & threshold < (-3)) {
`

i.e. handling _-Inf_ in exactly the same way as _NA_. However, we were still getting the same errors.

So, in a local version of PLMIX, I have changed the code directly in loglikPLMIX.cpp
At line 68, i.e. just before the line that updates h:

`h = h + weights[j]*exp(f) ;
`

I have added the following:

```
while(weights[j]*exp(f) == 0) {
  f++;
}
```

...which should ensure that the smallest (or very nearly smallest) possible non-zero value of _weights[j]*exp(f)_ is used, instead of _weights[j]*exp(f)_ equalling 0.

This fixes the issue, and was the best approximation I could come up with.

If you would prefer me to submit this change as a pull request, let me know.

All the best,
Chris Wirth
<christopherwirth@manchester.ac.uk>

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by christopherwirth** [comment]
Thanks, and apologies for the confusion. I have now emailed the maintainer directly.
